<h1>Terms of Use</h1>

<p>Welcome to the Lifestyle Management Programs provided by SelfHelpWorks.com Inc and its Distribution Partners. This site (this ""Site"") is comprised of various Web pages owned and operated by SelfHelpWorks.com, Inc. or its affiliates (""SelfHelpWorks"") for:
Your personal information and use or
The purpose of you or your agents to make decisions regarding a potential business relationship with SelfHelpWorks.com Inc.</p>

<p>Your submission of information to and access and use of this Site is subject to the terms and conditions of the terms of service set forth below (the ""Terms of Service""). By submitting information to and/or accessing and browsing this Site you accept and agree to abide by, without limitation or qualification, the Terms of Service. If you do not agree to be bound by the Terms of Service, you may not use this Site. IMPORTANT -- YOU MUST READ THIS CAREFULLY BEFORE USING THIS SITE. BY ENTERING THIS SITE, YOU AGREE TO BE BOUND BY ALL OF THE TERMS OF SERVICE. THIS SITE IS OWNED, CONTROLLED AND OPERATED BY SELFHELPWORKS.COM, INC. SELFHELPWORKS RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO MODIFY, ALTER OR OTHERWISE UPDATE THE TERMS OF SERVICE AT ANY TIME AND, BY ENTERING THIS SITE, YOU AGREE TO BE BOUND BY SUCH MODIFICATIONS, ALTERATIONS OR UPDATES AS WELL.</p>

<ol>
<li>THE SITE DOES NOT PROVIDE MEDICAL ADVICE. This Site offers online training programs, including smoking cessation, weight, and alcohol programs, designed to enable participants to break free of their addictive behavior, with a method called structural cognitive training (the ""Program""). The Site, and the Program, are for educational purposes only. Nothing contained in the Site, or the Program, is intended to be instructional for medical diagnosis or treatment. The information should not be considered complete, nor should it be relied on to suggest a course of treatment for a particular individual. The Program, and any other content such as text, graphics, images, information obtained from SelfHelpWorks' licensors, and other material, are not intended to be substitutes for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition, and before embarking on a new treatment, diet, or exercise program. Never disregard professional medical advice or delay in seeking such advice because of something you have read on the Site. If you think you may have a medical emergency, call your doctor or 911 immediately. SelfHelpWorks does not recommend or endorse any specific tests, products, procedures, opinions, or other information that may be mentioned on the Site. Reliance on any information provided by SelfHelpWorks, SelfHelpWorks employees, others appearing on the Site at the invitation of SelfHelpWorks, or other visitors to the Site is solely at your own risk. The Site may contain health or medical-related materials which you find explicit or otherwise offensive. SelfHelpWorks, its licensors, and its suppliers have no control over and accept no responsibility for such materials. You are solely responsible for compliance with the laws applicable to your country of residence.</li>

<li>Copyrights. All of the material on this Site, whether graphical, textual, audio, video, computer code, or software, or a combination thereof, are protected by copyrights which are owned and controlled by SelfHelpWorks, or by third parties that have licensed their material to SelfHelpWorks or are advertisers on www.selfhelpworks.com, and may not be copied, modified, reproduced, republished, posted, transmitted or distributed in any way without the express written permission from SelfHelpWorks. All contents of the Site are copyrighted under: Copyright Ã‚Â© 2001 SelfHelpWorks.com, Inc. All Rights Reserved. </li>

<li>Trademarks. www.selfhelpworks.com and the names of other SelfHelpWorks products and services referenced herein are trademarks of SelfHelpWorks.</li>

<li><p>License and Site Access. SelfHelpWorks grants you a limited license to
access and make personal use of this Site or
access and make use of this Site for the purpose of making decisions regarding a potential business relationship with SelfHelpWorks.com, Inc., and not to download (other than page caching) or modify it, or any portion of it, except with prior express written consent of SelfHelpWorks.</p>

<p>This license does not include any resale or commercial use of this Site or its contents; any collection and use of any product or service listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant or service provider; or any use of data mining, robots, or similar data gathering and extraction tools. This Site or any portion of this Site may not be reproduced, duplicated, copied, sold, resold, visited or otherwise exploited for any commercial purpose without the express written consent of SelfHelpWorks. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of SelfHelpWorks and our affiliates without our prior express written consent. You may not use any meta-tags or any other ""hidden text"" utilizing SelfHelpWorksÃ¢â‚¬â"¢ name or trademarks without the express written consent of SelfHelpWorks. Any unauthorized use terminates the permission or license granted by SelfHelpWorks. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of SelfHelpWorks so long as the link does not portray SelfHelpWorks, its affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any SelfHelpWorks logo or other proprietary graphic or trademark as part of the link without express written permission.</p> </li>

<li>Submission of Information. If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. SelfHelpWorks and its affiliates reserve the right to refuse service, terminate accounts, remove or edit content. Any communication or material you transmit to the web site by electronic mail or otherwise, including any data, questions, comments, suggestions, or the like is, and will be treated as, non-confidential and non-proprietary. Anything you transmit or post becomes the property of SelfHelpWorks, and may be used for any purpose, including, but not limited to, reproduction, disclosure, transmission, publication, broadcast and posting. </li>

<li>Use of Information. This Site contains information which may be derived in whole or in part from materials and information supplied by other sources. SelfHelpWorks makes no representation or warranty, express or implied, and assumes no responsibility or legal liability for the accuracy, completeness, timeliness or quality of any information contained in this Site, which is subject to deletion, addition and change at any time without notice from SelfHelpWorks. SelfHelpWorks does not ensure the accuracy, endorse or recommend any information and your use of any such information is at your own risk. The information contained on this Site cannot be considered complete and SelfHelpWorks undertakes no commitment to update the information contained on this Site within a particular period of time. It is the responsibility of each user of any portion of the Site to ascertain the accuracy of any information before entering into any commitment (financial or otherwise) or undertaking any course of action based upon the information contained in this Site. </li>

<li>Disclaimer of Warranties. THE USE OF THE SELFHELPWORKS SITE AND THE PROGRAM IS AT YOUR OWN RISK. ALL OF THE INFORMATION, SERVICES AND MATERIALS ON THIS SITE ARE PROVIDED ""AS IS"" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NO INFORMATION, ADVICE, OR GUIDANCE, WHETHER ORAL OR WRITTEN, RECEIVED BY YOU FROM SELFHELPWORKS OR THIS SITE SHALL CREATE ANY WARRANTY. </li>

<li>Limitation of Liability. IN NO EVENT SHALL SELFHELPWORKS BE LIABLE TO ANY PERSON OR ENTITY, INCLUDING, WITHOUT LIMITATION, PERSONS OR ENTITIES WHO MAY SUBMIT INFORMATION TO, USE OR RELY ON THIS SITE OR TO WHOM ANY INFORMATION ON THIS SITE MAY BE FURNISHED, FOR ANY LOSS OR DAMAGE OF ANY KIND OR CHARACTER WHATSOEVER, WHETHER DIRECT, INDIRECT, CONSEQUENTIAL, PERSONAL INJURY/WRONGFUL DEATH, SPECIAL, PUNITIVE OR OTHERWISE, ARISING OUT OF, BASED UPON OR RESULTING FROM ANY USE OF OR RELIANCE ON THIS SITE OR ANY INFORMATION OR OPINIONS CONTAINED HEREIN, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE. SELFHELPWORKS IS NOT LIABLE FOR ANY PERSONAL INJURY, INCLUDING DEATH, CAUSED BY YOUR USE OR MISUSE OF THE SITE, OR THE PROGRAM. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE FOREGOING LIMITATION MAY NOT APPLY TO YOU. FURTHER, SELFHELPWORKS SHALL NOT BE IN ANY WAY RESPONSIBLE FOR THE CONDUCT OR OMISSIONS OF THIRD PARTIES THAT HAVE POSTED INFORMATION ON THIS SITE OR FOR ANY INFORMATION POSTED ON THIS SITE BY SUCH PARTIES. </li>

<li>Third Party Sites. As a convenience to users, SelfHelpWorks may provide links on the Site to Web sites maintained by others. SelfHelpWorks has not necessarily reviewed such sites and is not responsible for the contents or availability of such sites or for products or services offered on such sites. SelfHelpWorks shall not be responsible or liable, directly or indirectly, for any damage or loss caused or claimed to have been caused by use of any such sites or the content, goods, services, or advertisements contained on or available via such sites. Links have been provided for your convenience and the inclusion of any link does not imply endorsement by SelfHelpWorks of the site or any association with the siteÃ¢â‚¬â"¢s owners or operators. </li>

<li>Privacy Policy. Pursuant to SelfHelpWorks privacy policy, we may disclose to third parties certain aggregate information contained in your registration or other information or related data, provided that, such information will not include personally identifying information, except as specifically authorized by you or in the good faith belief that such action is reasonably necessary to comply with the law, legal process, to enforce the Terms of Service, or under any of the other circumstances set forth in our privacy policy, as may be amended from time to time. </li>

<li>Indemnification. Each user of this Site agrees to indemnify, defend and hold SelfHelpWorks harmless from and against any and all third party claims, liabilities, costs, or expenses, including reasonable attorneys fees, arising out of or resulting from (a) such user's breach of any provision of these Terms of Service, (b) such user's negligence or willful misconduct, or (c) a claim that information submitted to this Site infringes the intellectual property or proprietary rights of a third party. </li>

<li>General. This Site is controlled and operated by SelfHelpWorks from its offices within the State of California, United States of America. SelfHelpWorks makes no representation that the materials on this Site are appropriate or available for use in other locations. Those who choose to access this Site from other locations do so on their own initiative and at their own risk and are responsible for compliance with local laws, if and to the extent applicable. These Terms of Service shall be governed by and construed and enforced in accordance with the laws of the State of California, without regard to conflicts of law, as they are applied to agreements entered into and to be performed entirely within the State of California. Any action you, any third party, or SelfHelpWorks brings to enforce these Terms of Service or in connection with any matters relating to this Site shall be brought only in either the state or federal courts located in San Diego County, California, and you expressly consent to the jurisdiction of said courts. If any provision of these Terms of Service shall be unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Service and shall not affect the validity and enforceability of any remaining provisions. These Terms of Service constitute the entire agreement and understanding between you and SelfHelpWorks and supersede any prior or contemporaneous agreements or understandings, whether written or oral, relating to the matters contained herein. </li>

<li>Term and Termination. These Terms of Service are effective until terminated by either you or SelfHelpWorks. You may terminate the Terms of Service at any time by discontinuing your use of this Site and destroying all materials obtained from it. The provisions contained under the headings Copyrights, Trademarks, Disclaimer of Warranties, Limitation of Liability, Indemnification and General shall survive any such termination.</li>